chore: update

diff --git a/.github/workflows/nextjs.yml b/.github/workflows/nextjs.yml
--- a/.github/workflows/nextjs.yml
+++ b/.github/workflows/nextjs.yml
@@ -7,7 +7,7 @@ name: Deploy Next.js site to Pages
 on:
   # Runs on pushes targeting the default branch
   push:
-    branches: ["main"]
+    branches: ['main']
 
   # Allows you to run this workflow manually from the Actions tab
   workflow_dispatch:
@@ -21,7 +21,7 @@ permissions:
 # Allow only one concurrent deployment, skipping runs queued between the run in-progress and latest queued.
 # However, do NOT cancel in-progress runs as we want to allow these production deployments to complete.
 concurrency:
-  group: "pages"
+  group: 'pages'
   cancel-in-progress: false
 
 jobs:
@@ -36,36 +36,38 @@ jobs:
       - name: Setup Node
         uses: actions/setup-node@v4
         with:
-          node-version: "20"
+          node-version: '20'
           cache: ${{ steps.detect-package-manager.outputs.manager }}
       - name: Detect package manager
         id: detect-package-manager
         run: |
-         if [ -f "${{ github.workspace }}/pnpm-lock.yaml" ]; then
-            echo "manager=pnpm" >> $GITHUB_OUTPUT
-            echo "command=install" >> $GITHUB_OUTPUT
-            echo "runner=pnpm" >> $GITHUB_OUTPUT
-            exit 0
-          elif [ -f "${{ github.workspace }}/yarn.lock" ]; then
-            echo "manager=yarn" >> $GITHUB_OUTPUT
-            echo "command=install" >> $GITHUB_OUTPUT
-            echo "runner=yarn" >> $GITHUB_OUTPUT
-            exit 0
-          elif [ -f "${{ github.workspace }}/package.json" ]; then
-            echo "manager=npm" >> $GITHUB_OUTPUT
-            echo "command=ci" >> $GITHUB_OUTPUT
-            echo "runner=npx --no-install" >> $GITHUB_OUTPUT
-            exit 0
-          else
-            echo "Unable to determine package manager"
-            exit 1
-          fi
+          if [ -f "${{ github.workspace }}/pnpm-lock.yaml" ]; then
+             echo "manager=pnpm" >> $GITHUB_OUTPUT
+             echo "command=install" >> $GITHUB_OUTPUT
+             echo "runner=pnpm" >> $GITHUB_OUTPUT
+             exit 0
+           elif [ -f "${{ github.workspace }}/yarn.lock" ]; then
+             echo "manager=yarn" >> $GITHUB_OUTPUT
+             echo "command=install" >> $GITHUB_OUTPUT
+             echo "runner=yarn" >> $GITHUB_OUTPUT
+             exit 0
+           elif [ -f "${{ github.workspace }}/package.json" ]; then
+             echo "manager=npm" >> $GITHUB_OUTPUT
+             echo "command=ci" >> $GITHUB_OUTPUT
+             echo "runner=npx --no-install" >> $GITHUB_OUTPUT
+             exit 0
+           else
+             echo "Unable to determine package manager"
+             exit 1
+           fi
       - name: Add pnpm to PATH
         run: echo "${{ github.workspace }}/node_modules/.bin" >> $GITHUB_PATH
       - name: Install dependencies
         run: pnpm ${{ steps.detect-package-manager.outputs.command }}
       - name: Build with Next.js
         run: ${{ steps.detect-package-manager.outputs.runner }} build
+      - name: Setup Pages
+        uses: actions/configure-pages@v4
       - name: Upload artifact
         uses: actions/upload-pages-artifact@v3
         with:
